name: Hello CI

on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Say hi
        run: echo "Hello, $GITHUB_ACTOR! Commit $GITHUB_SHA on $GITHUB_REF"
